version: '3.7'
services:
  mysql:
    image: mysql/mysql-server:8.0.27
    hostname: mysql
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=debezium
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpw
    volumes:
      - ${PWD}/infra/mysql/mysql.cnf:/etc/mysql/conf.d
      - ${PWD}/infra/mysql/mysql_bootstrap.sql:/docker-entrypoint-initdb.d/mysql_bootstrap.sql
    healthcheck: {test: mysql -pdebezium -e 'select 1', interval: 1s, start_period: 60s}